### ISSUE TITLE
[ 1.5.0rc2 ] : Allowing log verbosity configuration in the "elasticsearch" output.

### ISSUE THREAD

**Issue by chiriaev** [logstash-plugins/logstash-input-heartbeat#5]
Guys, Hi. I am testing the latest "1.5.0 rc2". I have a couple of Rabbit inputs with four threads each. The output uses the latest "elasticsearch" plugin. There is one very annoying difference between the latter and the deprecated "elasticsearch_http" plugin. Any "POST /_bulk" response with one or more records with a "status" of, for example, 400 or 429, etc..., will generate "warn" level log data corresponding to the original bulk request. In my case I can have dozens of megabytes per seconds. A configuration option controlling this behaviour would be mostly welcome. (i.e.: the Rabbit input has it by the way)

Thanks in advance.

Regards, Andrei

P.S.: transferred from https://github.com/elastic/logstash/issues/2847

**Comment by untergeek** [comment]
Please re-submit to the correct repository:  https://github.com/logstash-plugins/logstash-output-elasticsearch

**Comment by chiriaev** [comment]
Sorry, not sure what happened. Done @ https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/75 Regards, Andrei
